name: "telegram-report-bot"
services:
    bot:
        image: "groosha/telegram-report-bot:latest"
        restart: "always"
        stop_signal: SIGINT
        environment:
            - CONFIG_FILE_PATH=/app/settings.toml
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            # Pass your settings toml to container
            - "/path/to/your/settings.toml:/app/settings.toml:ro"
            # In case you want to use another locale
            - "/path/to/custom/locale/strings.ftl:/app/bot/locale/current/strings.ftl:ro"
