version: "3.8"
services:
    bot:
        image: groosha/telegram-report-bot:latest
        container_name: "telegram-report-bot"
        restart: always
        environment:
            - BOT_TOKEN=${BOT_TOKEN}
            - BOT_LANGUAGE=${BOT_LANGUAGE}
            - GROUP_MAIN=${GROUP_MAIN}
            - GROUP_REPORTS=${GROUP_REPORTS}
        volumes:
            - /etc/localtime:/etc/localtime:ro
